=== ryales/fallen_timbers/ftAccounts.xsd
<?xml version="1.0"?>

<!-- RACHEL YALES                              -->
<!-- INSTG037 XML FINAL PROJECT                -->
<!-- INSTRUCTOR: SIMON MAHONY                  -->
<!-- SCHEMA FOR FALLEN TIMBERS BATTLE ACCOUNTS -->

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  	<!-- ROOT ELEMENT -->
  	<xs:element name="ftAccounts">
      <xs:complexType>
        <xs:sequence>
          <!-- ELEMENT FOR EACH INDIVIDUAL ACCOUNT: NO UPPER LIMIT ON NUMBER OF DOCUMENTS -->
          <xs:element name="ftAccount" maxOccurs="unbounded">
            <xs:complexType mixed="true">
              <xs:sequence>
                <!-- BIBLIOGRAPHIC INFO ABOUT THE DOCUMENT SOURCE -->
                <xs:element name="bibInfo">
                  <xs:complexType>
                    <!-- ONLY 0 OR 1 OF EACH ELEMENT: ORDER DOES NOT MATTER -->
                    <xs:all>
                      <xs:element name="pubArticle" type="xs:string" minOccurs="0"/>
                      <xs:element name="pubTitle" type="xs:string"/>
                      <!-- PUBAUTHOR CALLS TO GLOBAL PERSON ELEMENT -->
                      <xs:element name="pubAuthor">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element ref="person"/>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <!-- PUBEDITOR CALLS TO GLOBAL PERSON ELEMENT -->
                      <xs:element name="pubEditor" minOccurs="0">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element ref="person"/>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="pubName" type="xs:string"/>
                      <xs:element name="pubVol" type="xs:integer" minOccurs="0"/>
                      <xs:element name="pubIss" type="xs:integer" minOccurs="0"/>
                      <xs:element name="pubColl" type="xs:string" minOccurs="0"/>
                      <!-- PUBPLACE IS AN EMPTY ELEMENT WITH ATTRIBUTES -->
                      <xs:element name="pubPlace" minOccurs="0">
                        <xs:complexType>
                          <xs:attribute name="city" type="xs:string"/>
                          <xs:attribute name="state" type="xs:string"/>
                          <xs:attribute name="country" type="xs:string"/>
                        </xs:complexType>
                      </xs:element>
                      <!-- PUBDATE HAS DATATYPE GYEAR BECAUSE NO NEED FOR SPECIFIC DATE -->
                      <xs:element name="pubDate" minOccurs="0">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="date" type="xs:gYear"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="pubPage" type="xs:string" minOccurs="0"/>
                    </xs:all>
                    <!-- BIBINFO ATTRIBUTES CLASSIFY DOCUMENT SOURCE -->
                    <xs:attribute name="medium" type="xs:string" use="required"/>
                    <xs:attribute name="distance" type="xs:string" use="required"/>
                    <xs:attribute name="format" type="xs:string" use="required"/>
                    <xs:attribute name="text" type="xs:string" use="required"/>
                  </xs:complexType>
                </xs:element>
                <!-- DOCUMENT TEXT -->
                <xs:element name="account">
                  <xs:complexType>
                    <xs:sequence>
                      <!-- NOT EVERY DOCUMENT HAS HEADER -->
                      <!-- CALLS TO GLOBAL ELEMENTS -->
                      <xs:element name="header" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:element ref="place"/>
                            <xs:element ref="date"/>
                          </xs:choice>
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE OPENINGS -->
                      <xs:element name="opening" minOccurs="0">
                        <xs:complexType mixed="true">
                        </xs:complexType>
                      </xs:element>
                      <!-- UNLIMITED NUMBER OF PARAGRAPHS ALLOWED -->
                      <!-- CALLS TO GLOBAL ELEMENTS -->
                      <xs:element name="para" maxOccurs="unbounded">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                              <xs:element ref="action"/>
                              <xs:element ref="description"/>
                            </xs:choice>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE CLOSINGS -->
                      <xs:element name="closing" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                              <xs:element ref="person"/>
                            </xs:choice>
                          </xs:sequence> 
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE ADDRESSEE SECTION -->
                      <xs:element name="addressee" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                              <xs:element ref="person"/>
                            </xs:choice>
                          </xs:sequence>    
                        </xs:complexType>
                      </xs:element>
                      <!-- SOME LETTER DOCUMENTS HAVE POSTSCRIPTS -->
                      <xs:element name="postscript" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                              <xs:element ref="action"/>
                              <xs:element ref="description"/>
                            </xs:choice>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <!-- EACH FTACCOUNT HAS UNIQUE ID -->
              <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:complexType> 
          </xs:element>
        </xs:sequence>
      </xs:complexType>
  	</xs:element>
    
    <!-- GLOBAL ELEMENTS CONTAINED BELOW -->
    <!-- CAN BE USED IN MULTIPLE CONTEXTS -->
    <xs:element name="person">  
      <xs:complexType mixed="true">
        <xs:all>
          <xs:element name="pRank" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stRank" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>
          <xs:element name="pGiven" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stGiven" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
          <xs:element name="pSurname" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stSurname" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
          <xs:element name="pTitle" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stTitle" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
        </xs:all>
        <!-- Each unique person required to have an ID -->
        <xs:attribute name="pID" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="place">  
      <xs:complexType  mixed="true">
        <xs:attribute name="lat" type="xs:float"/>
        <xs:attribute name="long" type="xs:float"/>
        <!-- Each unique place required to have an ID -->
        <xs:attribute name="placeID" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="date">  
      <xs:complexType  mixed="true">
        <xs:attribute name="when" type="xs:date"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="unit">  
      <xs:complexType  mixed="true">
        <xs:attribute name="name" type="xs:string"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="action">  
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="person"/>
            <xs:element ref="unit"/>
            <xs:element ref="place"/>
            <xs:element ref="date"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="actCat" type="xs:string" use="required"/>
        <xs:attribute name="who" type="xs:string"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="description">  
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="person"/>
            <xs:element ref="unit"/>
            <xs:element ref="place"/>
            <xs:element ref="date"/>
            <xs:element name="weather">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="weatherID" type="xs:string"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="desCat" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:element>
  </xs:schema>

=== ryales/fallen_timbers/xml/04.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ftaccounts.xsl"?>

<ftAccounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ftAccounts.xsd">
  <ftAccount id="04">
    <bibInfo medium="journal" distance="primary" format="article" text="edited_reprint">
      <pubTitle>William Clark's Journal of General Wayne's Campaign</pubTitle>
      <pubAuthor>
        <person pID="">
          <pGiven>William</pGiven>
          <pSurname>Clark</pSurname>
        </person>
      </pubAuthor>
      <pubEditor>
        <person pID="">
          <pGiven>R. C.</pGiven>
          <pSurname>McGrane</pSurname>
        </person>
      </pubEditor>
      <pubName>The Mississippi Valley Historical Review</pubName>
      <pubVol>1</pubVol>
      <pubIss>3</pubIss>
      <pubDate date="1914">1914</pubDate>
      <pubPage>428-430</pubPage>
    </bibInfo>
    <account>
      <header>
        <date when="1794-08-20">20th August 94</date>&#8212;
      </header>
      <para>
        <description desCat="weather">A <weather>sower of Rain</weather> prevented our move at the
        houre appointed</description>, but <action actCat="movement" who="US Army">we took up the Line of March at 7 o'Clock</action> and
        <description desCat="landscape">found the way extremely bad, much embarrassed by the thickness of
        the woods on the left and by a number of Steep Reviens on the Right</description>,
        after proceeding about 2 hours <action actCat="battle" who="Front Guard">our Spies &amp; advance guard Discovered
        the Enemy and received their fire</action>, but <action actCat="movement" who="Front Guard">with inconsiderable Loss were
        driven back and joined the main Body of the Army</action>, by this time <action actCat="battle" who="2nd and 4th Sub-legions">the
        Right division, Comded by <person pID="02"><pRank stRank="Brigadier General">Genl.</pRank> <pSurname>Wilkinson</pSurname></person> felt the effects of the Enemeys
        fire, they was immediately formed &amp; returned the fire</action>, at this period
        <action actCat="battle" who="Right Dragoons"><person pID=""><pRank>Capt.</pRank> <pSurname>Campbell</pSurname></person> troop made a charge in which he fell &amp; his Troop immediately
        proceeded through surported by the Infantry's charge</action> which
        <action actCat="battle" who="Native Confederacy">oblidged the enemey to quit theire position and look for more advantagous
        ground. on our Left &amp; they made an exertion to gaine that Flank</action>
        but <action actCat="battle" who="1st and 3rd Sub-legions"><person pID="23"><pRank>Colo</pRank> <pSurname>Hamtramck</pSurname></person> who commanded in that Quarter was perpared &amp;
        gave them so warm a recption as made theire Situation here as disagreeable
        as that on the Right</action>, and <action actCat="battle" who="US Legion">the charge both on the Right &amp; left both
        became Genl. &amp; the Enemy was repulsed with precipation</action>; <action actCat="battle" who="Kentucky Volunteers Cavalry">The charge
        of the Cavelry closed the seene in front &amp; drove the Enemey 3/4 of a
        mile at the same instant</action>, <action actCat="battle" who="Left Flank">The Riflemen &amp; Light Infantry, receved a
        most heavy fire, on the extreem left flank</action>, <action actCat="casualty" who="US Officers">The Entrepid <person pID="04"><pRank stRank="Lieutenant">Lieut.</pRank> <pSurname stSurname="Towles">Towls</pSurname></person>
        fell</action> at this fire, <action actCat="battle" who="US Army">We drove the Enemy for about one mile directly out</action>,
        with <action actCat="casualty" who="US Army">the Loss of <person pID="04"><pRank stRank="Lieutenant">Lieut.</pRank> <pSurname stSurname="Towles">Towls</pSurname></person> &amp; a fiew Infantry on our Side</action>, in this
        quater <action actCat="casualty" who="Native Confederacy">was Killed 3 white men &amp; several Indians mostly by the Riflemen</action>.
        <action actCat="rest" who="US Army">the Troops were now refreshed with 1/2 a gill of Whiskey</action> which
        they much required as <description desCat="duration">the action continued more then an houre, the
        greater part of which time they were in full Speed pressing the Enemey</description>&#8212;after
        remaining on this ground a fiew hours <action actCat="rest" who="US Army">Dureing which time the
        wounded were Brought in Dressed &amp;c</action> <action actCat="movment" who="US Army">we proceeded within about one
        mile of the British Garrison and there took up our Encampment</action>.
      </para>
      <para>
        <description desCat="criticism">I shall now make a fiew observations or reflections on the Buisness of
        this day. Had the Enemey for once forsaken theire long established
        mode of fighting (Viz) that of extending theire lines so as to gaine the
        flanks of theire advasary&#8212;for by this means they so weakened themselves
        in all points as not to be able to make but a feable resistance in
        any one, much less beat &amp; confuse the lines of theire opposers, which in
        this case they might have easily done, had they kept themselves compact
        and advanced with Judgement. (I say had the Enemey been formed in
        tolerable close orders and advanced in the first instance, close on the heals
        of our retireing Spies &amp; Advanced guard, I am Satisfied they would
        have made a Breach in any part of our Columns as our Front was so extended
        as to render the whole in any one part, unequal to the resistants
        of a well formed body rapidly advancing on them, besides our orders or
        mode of Formation required very considerable time to performe the perparitory
        Evolutions: on the other hand, had the Kentucky Volunters
        (who composed half of our forces) been so disposed of as to have
        gained the reare of the Enemy soon after they commenced the attack,
        Then I am Satisfied we should had the pleasure of seeing every Head of
        this dreaded Hydra at our feet; but from theire Situation or (as some
        say for the want of orders) they were so far from gaining this grand
        position, that not more then 300 out of 1500 well mounted Riflemen were
        ever brought to action, and they but a fiew moments. Cannot but be
        astonished when the world informed that the <person pID="01"><pTitle stTitle="Commander in Chief">Comdr in Chief</pTitle></person> had been
        told on the day previous to the action, by an officere of Rank an credebillity
        (<person pID="34"><pRank stRank="Major">Majr</pRank> <pSurname>Price</pSurname></person> of the Volunteers who commd a sort of Independant
        partizan-corps and had been sent for the Express purpose) that the
        Enemey were laying in wait for us &amp; formed in Such a possition" &amp; also
        gave His Excellency an exact Discription of the ground I say, the
        whole world cannot but be surprised that the <person pID="01"><pTitle stTitle="Commander in Chief">Comdr in Chief</pTitle></person> did not
        availe himself of this advantage &amp; by throwing the Voluntiers in the
        reare of the Enemey &amp; eventually cut off theire retreat: but so far was
        his Excelcy from thus putting an end to this expensive war (I believe
        that the atack of the Enemey at the time it happined was actually a matter
        of Surprise to almost every officer in the army</description>&#8212;<action actCat="burial" who="US Army">The Bodies of Capt.
        Campbell &amp; <person pID="04"><pRank>Lieutenant</pRank> <pSurname>Towles</pSurname></person> (the only officers killed) were entered
        immediately after the action.</action> <action actCat="casualty" who="US Army">The whole ammount of the Killed on our
        part were 240</action> <action actCat="casualty" who="Native Confederacy">the loss of the Enemey not precisely ascertained but not
        more than 30 or 40 were found Dead, and a fiew Canadians</action> <action actCat="prisoner" who="US Army">one was
        taken prisoner, who was a treader amoung the Indians</action>, and says <description desCat="strength">they opposed
        us with about 900 Indians &amp; 150 Canadians</description>.
      </para>
    </account>
  </ftAccount>
</ftAccounts>

=== ryales/fallen_timbers/xml/03.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ftaccounts.xsl"?>

<ftAccounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ftAccounts.xsd">
  <ftAccount id="03">
    <bibInfo medium="journal" distance="primary" format="book" text="edited_original">
      <pubTitle>A Journal of Wayne's Campaign: Being an Authentic Daily Record of the most Important Occurrences during the Campaign of Major General Anthony Wayne, against the Northwestern Indians; Commencing on the 28th day of July, and ending on the 2d day of November, 1794; including an account of the great battle of August 20th</pubTitle>
      <pubAuthor>
        <person pID="20">
          <pGiven>John</pGiven>
          <pSurname>Boyer</pSurname>
        </person>
      </pubAuthor>
      <pubName>Jno. F. Uhlhorn</pubName>
      <pubPlace city="Cincinnati" state="Ohio"></pubPlace>
      <pubDate date="1866">1866</pubDate>
      <pubPage>7-8</pubPage>
    </bibInfo>
    <account>
      <header>
        <place placeID="02">Camp in sight of a British garrison, on the Miamis of the Lake</place>,
        <date when="1794-08-20">August 20th, 1794</date>&#8212;one hundred and fifty miles from <place placeID="03">Greenville</place>.
      </header>
      <para>
        This day <action actCat="preparation" who="US Legion">the legion, after depositing every kind of baggage</action>,
        <action actCat="movement" who="US Legion">took up the line of march at 7 o'clock, and continued their
        route down the margin of the river, without making any
        discovery</action>, until <action actCat="battle" who="Front Guard">11 o'clock, when the front guard, which was
        composed of mounted volunteers, were fired on by the enemy</action>.
        <action actCat="movement" who="Front Guard">The guard retreated in the utmost confusion through the front
        guard of the regulars, commanded by <person pID="14"><pRank>Captain</pRank> <pSurname>Cook</pSurname></person> and
        <person pID="13"><pRank>Lieutenant</pRank> <pSurname>Steele</pSurname></person>, who, in spite of their utmost exertion,
        made a retreat.</action> <action actCat="battle" who="US Legion">These fell in with the left of <person pID="15"><pRank>Captain</pRank>
        <pGiven>Howell</pGiven> <pSurname>Lewis</pSurname></person>' company of light infantry and threw that part
        of the men into confusion</action>, which <action actCat="battle" who="US Legion"><person pID="15"><pRank>Captain</pRank> <pSurname>Lewis</pSurname></person> observing, he
        ordered the left of his company to retreat about forty yards,
        where he formed them and joined the right, which had stood
        their ground</action>. <action actCat="battle" who="US Legion">They continued in this position until they
        were joined by part of <person pID="16"><pRank>Captain</pRank> <pSurname>Springer</pSurname></person>'s battalion of riflemen,
        which was nearly fifteen minutes after the firing commenced,
        who drove the enemy that had attempted to flank us on the
        right</action>. Nearly at the same time, <action actCat="movement" who="1st and 3rd Sub-legions">the right column came up,
        and the charge was sounded</action>&#8212;<action actCat="movement" who="Native Confederacy">the enemy gave way and fired
        scattering shots as they run off</action>.
      </para>
      <para>
        About the time the right column came up, <action actCat="battle" who="2nd and 4th Sub-legions">a heavy firing
        took place on the left, which lasted but a short time</action>, <action actCat="movement" who="Native Confederacy">the
        enemy giving way in all quarters</action>, which left us in possession
        of <action actCat="casualty" who="Native Confederacy">their dead to the number of forty</action>. <action actCat="casualty" who="US Army">Our loss was thirty
        killed and one hundred wounded.</action> Among the former we have to lament <action actCat="casualty" who="US Officers">the loss of <person pID="05"><pRank>Captain</pRank> <pSurname stSurname="Mis Campbell">Miss Campbell</pSurname></person> of the
        dragoons, and <person pID="04"><pRank>Lieutenant</pRank> <pGiven stGiven="Henry Beverly">Henry B.</pGiven> <pSurname stSurname="Towles">Fowles</pSurname></person> of the 4th sub-legion;
        and of the latter, <person pID="18"><pRank stRank="Captain">Captains</pRank> <pSurname>Prior</pSurname></person> of the first, <person pID="17"><pSurname>Slough</pSurname></person>
        of the fourth, and <person pID="10"><pSurname>Van Rensselaer</pSurname></person> of the dragoons, also
        <person pID="19"><pRank>Lieutenant</pRank> <pGiven>Campbell</pGiven> <pSurname>Smith</pSurname></person> of the fourth sub-legion</action>. <description desCat="speculation">The
        whole loss of the enemy cannot at present be ascertained, but
        it is more than probable it must have been considerable</description>, for
        <action actCat="movement" who="US Army">we pursued them with rapidity for nearly two miles</action>. <description desCat="strength">As to
        the number of the enemy engaged in this action, opinions are
        so various that <person pID="20">I</person> am at a loss to know what to say; the most
        general opinion is one thousand five hundred, one-third of
        which are supposed to be Canadians; I am led to believe this
        number is not over the mark</description>. After <action actCat="rest" who="US Army">the troops had taken
        some refreshment</action>, <action actCat="movement" who="US Legion">the legion continued their route down the
        river, and encamped in sight of the British garrison</action>. <action actCat="prisoner" who="US Army">One
        Canadian fell into our hands, who we loaded with irons.</action>
      </para>
    </account>
  </ftAccount>
</ftAccounts>
