=== ryales/fallen_timbers/ftAccounts.xsd
<?xml version="1.0"?>

<!-- RACHEL YALES                              -->
<!-- INSTG037 XML FINAL PROJECT                -->
<!-- INSTRUCTOR: SIMON MAHONY                  -->
<!-- SCHEMA FOR FALLEN TIMBERS BATTLE ACCOUNTS -->

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  	<!-- ROOT ELEMENT -->
  	<xs:element name="ftAccounts">
      <xs:complexType>
        <xs:sequence>
          <!-- ELEMENT FOR EACH INDIVIDUAL ACCOUNT: NO UPPER LIMIT ON NUMBER OF DOCUMENTS -->
          <xs:element name="ftAccount" maxOccurs="unbounded">
            <xs:complexType mixed="true">
              <xs:sequence>
                <!-- BIBLIOGRAPHIC INFO ABOUT THE DOCUMENT SOURCE -->
                <xs:element name="bibInfo">
                  <xs:complexType>
                    <!-- ONLY 0 OR 1 OF EACH ELEMENT: ORDER DOES NOT MATTER -->
                    <xs:all>
                      <xs:element name="pubArticle" type="xs:string" minOccurs="0"/>
                      <xs:element name="pubTitle" type="xs:string"/>
                      <!-- PUBAUTHOR CALLS TO GLOBAL PERSON ELEMENT -->
                      <xs:element name="pubAuthor">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element ref="person"/>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <!-- PUBEDITOR CALLS TO GLOBAL PERSON ELEMENT -->
                      <xs:element name="pubEditor" minOccurs="0">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element ref="person"/>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="pubName" type="xs:string"/>
                      <xs:element name="pubVol" type="xs:integer" minOccurs="0"/>
                      <xs:element name="pubIss" type="xs:integer" minOccurs="0"/>
                      <xs:element name="pubColl" type="xs:string" minOccurs="0"/>
                      <!-- PUBPLACE IS AN EMPTY ELEMENT WITH ATTRIBUTES -->
                      <xs:element name="pubPlace" minOccurs="0">
                        <xs:complexType>
                          <xs:attribute name="city" type="xs:string"/>
                          <xs:attribute name="state" type="xs:string"/>
                          <xs:attribute name="country" type="xs:string"/>
                        </xs:complexType>
                      </xs:element>
                      <!-- PUBDATE HAS DATATYPE GYEAR BECAUSE NO NEED FOR SPECIFIC DATE -->
                      <xs:element name="pubDate" minOccurs="0">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="date" type="xs:gYear"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="pubPage" type="xs:string" minOccurs="0"/>
                    </xs:all>
                    <!-- BIBINFO ATTRIBUTES CLASSIFY DOCUMENT SOURCE -->
                    <xs:attribute name="medium" type="xs:string" use="required"/>
                    <xs:attribute name="distance" type="xs:string" use="required"/>
                    <xs:attribute name="format" type="xs:string" use="required"/>
                    <xs:attribute name="text" type="xs:string" use="required"/>
                  </xs:complexType>
                </xs:element>
                <!-- DOCUMENT TEXT -->
                <xs:element name="account">
                  <xs:complexType>
                    <xs:sequence>
                      <!-- NOT EVERY DOCUMENT HAS HEADER -->
                      <!-- CALLS TO GLOBAL ELEMENTS -->
                      <xs:element name="header" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:element ref="place"/>
                            <xs:element ref="date"/>
                          </xs:choice>
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE OPENINGS -->
                      <xs:element name="opening" minOccurs="0">
                        <xs:complexType mixed="true">
                        </xs:complexType>
                      </xs:element>
                      <!-- UNLIMITED NUMBER OF PARAGRAPHS ALLOWED -->
                      <!-- CALLS TO GLOBAL ELEMENTS -->
                      <xs:element name="para" maxOccurs="unbounded">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                              <xs:element ref="action"/>
                              <xs:element ref="description"/>
                            </xs:choice>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE CLOSINGS -->
                      <xs:element name="closing" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                              <xs:element ref="person"/>
                            </xs:choice>
                          </xs:sequence> 
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE ADDRESSEE SECTION -->
                      <xs:element name="addressee" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                              <xs:element ref="person"/>
                            </xs:choice>
                          </xs:sequence>    
                        </xs:complexType>
                      </xs:element>
                      <!-- SOME LETTER DOCUMENTS HAVE POSTSCRIPTS -->
                      <xs:element name="postscript" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                              <xs:element ref="action"/>
                              <xs:element ref="description"/>
                            </xs:choice>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <!-- EACH FTACCOUNT HAS UNIQUE ID -->
              <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:complexType> 
          </xs:element>
        </xs:sequence>
      </xs:complexType>
  	</xs:element>
    
    <!-- GLOBAL ELEMENTS CONTAINED BELOW -->
    <!-- CAN BE USED IN MULTIPLE CONTEXTS -->
    <xs:element name="person">  
      <xs:complexType mixed="true">
        <xs:all>
          <xs:element name="pRank" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stRank" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>
          <xs:element name="pGiven" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stGiven" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
          <xs:element name="pSurname" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stSurname" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
          <xs:element name="pTitle" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stTitle" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
        </xs:all>
        <!-- Each unique person required to have an ID -->
        <xs:attribute name="pID" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="place">  
      <xs:complexType  mixed="true">
        <xs:attribute name="lat" type="xs:float"/>
        <xs:attribute name="long" type="xs:float"/>
        <!-- Each unique place required to have an ID -->
        <xs:attribute name="placeID" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="date">  
      <xs:complexType  mixed="true">
        <xs:attribute name="when" type="xs:date"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="unit">  
      <xs:complexType  mixed="true">
        <xs:attribute name="name" type="xs:string"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="action">  
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="person"/>
            <xs:element ref="unit"/>
            <xs:element ref="place"/>
            <xs:element ref="date"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="actCat" type="xs:string" use="required"/>
        <xs:attribute name="who" type="xs:string"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="description">  
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="person"/>
            <xs:element ref="unit"/>
            <xs:element ref="place"/>
            <xs:element ref="date"/>
            <xs:element name="weather">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="weatherID" type="xs:string"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="desCat" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:element>
  </xs:schema>

=== ryales/fallen_timbers/xml/08.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ftaccounts.xsl"?>

<ftAccounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ftAccounts.xsd">
  <ftAccount id="08">
    <bibInfo medium="letter" distance="primary" format="book" text="edited_reprint">
      <pubArticle>
        From Alexander McKee to Joseph Chew
      </pubArticle>
      <pubAuthor>
        <person pID="24">
          <pRank>Colonel</pRank>
          <pGiven>Alexander</pGiven>
          <pSurname>McKee</pSurname>
        </person>
      </pubAuthor>
      <pubEditor>
        <person pID="48">
          <pRank>Brigadier General</pRank>
          <pGiven>E. A.</pGiven>
          <pSurname>Cruikshank</pSurname>
        </person>
      </pubEditor>
      <pubTitle>The Correspondence of Lieut. Governor John Graves Simcoe, with Allied Documents relating to his Administration of the Government of Upper Canada</pubTitle>
      <pubVol>3</pubVol>
      <pubName>
        Ontario Historical Society
      </pubName>
      <pubDate date="1925"></pubDate>
      <pubPlace city="Toronto" state="Ontario" country="Canada"></pubPlace>
      <pubPage>7-8</pubPage>
    </bibInfo>
    <account>
      <header>
        <place placeID="09">Camp, Near Fort Miamis</place>, <date when="1794-08-27">27th Aug 1794</date>.
      </header>      
      <opening>
        Dear Sir:
      </opening>
      <para>
        It was not possible for me sooner to communicate the events which have lately
        happened in this Country&#8212;<action actCat="movement" who="US Army"><person pID="01"><pRank>General</pRank> <pSurname>Wayne</pSurname></person> with an Army of Near 4000 men
        (according to the report of deserters) made gradual approaches towards us until
        his arrival at <place placeID="07">Roche de Bout</place> on the <date when="1794-08-17">17th Inst.</date>&#8212;where <person pID="01">he</person> fixed his head Quarters,
        on the 18th</action>&#8212;<action actCat="prisoner" who="Native Confederacy"><person pID="12">the <pTitle>Spy</pTitle> <pSurname>May</pSurname></person> was taken, who informed the Indians it was intended
        to attack them the Next day,&#8212;unless <person pID="01">the <pRank stRank="Major General">General</pRank></person> should determine to build a
        Fort, in which case he would not advance until the day following</action>, <action actCat="position" who="Native Confederacy">on the 19th the
        Indians to the number of 1300 marched Early to the most advantageous Ground</action>,
        but <action actCat="movement" who="US Cavalry">a strong detachment of Cavalry only made their appearance and retired as
        Soon as the Indians showed themselves</action>.
      </para>
      <para>
        <action actCat="battle">On the 20th the American Army advanced and were first attacked by the left
        of the center of the Indian line which extended near three quarters of a mile
        obliquely upward</action>,&#8212;<action actCat="battle">the Americans Soon gave way &amp; a rapid pursuit took place
        for about a mile where the Indian discovered the whole of the American Army
        Posted to whom they gave Battle retiring slowly before them</action>, during this period,
        <action actCat="battle" who="Native Confederacy">the Wyandot and Ottawas who were on the Right were Warmly Engaged by the
        American left consisting of both Cavalry and infantry who out flanked and infiladed
        the Indians until they retreated</action>&#8212;<action actCat="retreat" who="Native Confederacy">the whole line of the Indians then retired below
        <place placeID="08">the Fort</place> imagining their loss to be much greater then it since appears to have been</action>
        having seen <action actCat="casualty" who="Native Chiefs">several of their Principal Chiefs fall;&#8212;The greatest cost they have
          sustained is in their leaders</action> <action actCat="movement" who="Native Confederacy">they halted that night at Swan Creek about six miles
        below and were not pursued</action>, <description desCat="strength">there were never more than 400 Indians engaged during
        the whole day and these stood the shock of a great part of their Army for upwards
        of two hours</description> and <action actCat="casualty" who="Native Confederacy">lost in the whole but 19 men among whom are to be much lamented
        8 Principal Chiefs of the Wyondots and two of the Ottawas, besides two more
        wounded</action>&#8212;
      </para>
      <para>
        By the reports of several deserters and from a survey of the field of Action
        (for <action actCat="burial" who="US Army">they did not even bury but few of their dead</action>) <action actCat="casualty" who="US Army">it appears the Americans lost
        between 3 and 400 Killed and Wounded and a great many horses</action>.&#8212;The opperations
        of the Garrison I must leave to be detailed by those whose duty it is, but I must
        observe to you that <action actCat="destruction" who="US Army">all the store houses, my own House with many things that
        could not be removed were burnt by a Party of <person pID="01"><pRank>General</pRank> <pSurname>Wayne</pSurname></person>'s Army</action> within
        sight of the Garrison. I hope soon to have the pleasure of seeing you.&#8212;At present
        <action actCat="plan">I am waiting until the Indians whose Cornfields and Villages are totally destroyed
        Shall determine where they and their Families will set themselves down it being a
        matter of the highest importance to the Interest of Great Britain to prevent if
        possible their emigrating to the Southern and western parts of the Continent,
        they Seemingly now having lost all hopes of the Interference of Government.</action>&#8212;
      </para>
      <para>
        <action actCat="diplomacy">Some letters passed between <person pID="03"><pRank>Major</pRank> <pSurname>Campbell</pSurname></person> Commanding Fort Miamis
        &amp; <person pID="01"><pRank stRank="Major General">General</pRank> <pSurname>Wayne</pSurname></person> after the Action</action>, and <action actCat="movement" who="US Army">on the 22nd the American Army quited
        the position they had taken within a mile of the Fort, and retreated the very same
        way they came</action>, but whether on account of the want of Provisions, or of an order
        from Philadelphia cannot be Certainly known.&#8212;<action actCat="destruction" who="US Army">The American Army have left
        Evident marks of their boasted Humanity behind them besides scalping and mutilating
        the Indians who were killed in Action, they have opened the Peaceful Graves
        in different parts of the Country, Exposed the Bones of the consumed &amp; consuming
        bodies, and horrid to relate have with unparalleled barbarity driven stakes
        through them and left them objects calling for more than human Vengeance.</action>
      </para>
      <closing>
        I am with great Regard &amp; Esteem, Dear Sir
        Yours Very Sincerely
        <person pID="24"><pGiven stGiven="Alexander">A.</pGiven> <pSurname>McKee</pSurname></person>
      </closing>
      <addressee>
        Montreal 20th Sept 1794.
        A True Copy
        <person pID="44"><pGiven>Joseph</pGiven> <pSurname>Chew</pSurname>, <pTitle stTitle="Secretary of Indian Affairs">S.I.A.</pTitle></person>
      </addressee>
    </account>
  </ftAccount>
</ftAccounts>

=== ryales/fallen_timbers/xml/06.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ftaccounts.xsl"?>

<ftAccounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ftAccounts.xsd">
  <ftAccount id="06">
    <bibInfo medium="journal" distance="primary" format="article" text="edited_reprint">
      <pubArticle>A Journal of a Campaign in the Year 1794 Under the Command of Major General Charles Scott</pubArticle>
      <pubAuthor>
        <person pID="00">
          <pSurname>Anonymous</pSurname>
        </person>
      </pubAuthor>
      <pubEditor>
        <person pID="50">
          <pGiven>Richard C.</pGiven>
          <pSurname>Knopf</pSurname>
        </person>
      </pubEditor>
      <pubTitle>Two Journals of the Kentucky Volunteers 1793 and 1794</pubTitle>
      <pubName>The Filson Club Historical Quarterly</pubName>
      <pubVol>27</pubVol>
      <pubIss>3</pubIss>
      <pubDate date="1953">1953</pubDate>
      <pubPage>258-273; 279-281</pubPage>
		</bibInfo>
		<account>
			<header>
				Wednesday 20
			</header>
        <para>
          <description desCat="weather"><weather>Clear</weather></description>, <action actCat="preparation" who="US Army">The Baggage being Deposited, in <place placeID="01">the Fortification</place></action> <action actCat="movement" who="US Army">the
          Army moved at 6</action> in the following order <description desCat="position"><person pID="35"><pRank stRank="Captain">Capt</pRank> <pSurname>Baker</pSurname></person> &amp; <person pID="51"><pRank stRank="Captain">Capt</pRank>
          <pSurname>Arnold</pSurname></person>'s Companies under the Comd. of <person pID="34"><pRank stRank="Major">Majr.</pRank> <pSurname>Price</pSurname></person> formd. the Front
          or Corps of observation. <person pID="36"><pRank stRank="Brigadier General">Brigd. Genl.</pRank> <pSurname>Todd</pSurname></person> on the Left <person pID="02"><pRank stRank="Brigadier General">Genl.</pRank>
          <pSurname>Wilkinson</pSurname></person> on the Margin of the River the artillery and bagage in
          the Centre <person pID="37"><pRank stRank="Brigadier General">Genl</pRank> <pSurname>Barbee</pSurname></person> in the rear</description> <description desCat="landscape">the Ground for 5 miles high
          &amp; dry open Woods tall large Oaks</description> <action actCat="battle" who="Front Guard">at 45 Minutes past 8 the
          Front was attactd. by a number of Indians in the high Grass</action> <action actCat="battle" who="Front Guard">They
          returnd. the fire and fell back to the Front of the Federal Army, which
          likewise fell back untill They Formed the line of Battle</action> when <action actCat="battle" who="Right Dragoons">they
          movd. on driving the Enemy before them the Cavelry chargd.</action> here
          with <action actCat="casualty" who="Right Dragoons">the loss of the brave <person pID="05"><pRank stRank="Captain">Capt.</pRank> <pSurname stSurname="Mis Campbell">M. Campbell</pSurname></person> at this Time</action> <action actCat="movement" who="Kentucky Volunteer Cavalry"><person pID="36"><pRank stRank="Brigadier General">Genl</pRank>
          <pSurname>Todd</pSurname></person> Brigade was forming a line and immediately got into action
          after getting orders from <person pID="06"><pRank stRank="General">Genl.</pRank> <pSurname>Scott</pSurname></person> to dismount and move
          forwards</action> in <description desCat="landscape">a lo swampy ground with a great dale of
          fallen Timber and thick brush with Hoop and black Ash bushes which
          rendred the place difficult to see a Man 10 yds</description> <description desCat="duration">the action Continud
          all together 1 hour &amp; 20 Minutes with the Volunteers half an hour</description>
          when <action actCat="retreat" who="Native Confederacy">the Indians and their white allies part British and some French
          retired in a very precipitate manner</action> <action actCat="burial" who="Native Confederacy">leaving their dead and some of
          their wounded on the Field</action> <action actCat="burial" who="Kentucky Volunteers">we moved back over the ground
          collectd. the wounded</action> and moved to <action actCat="rest" who="US Army">the Federal troops where they
          were haltd and had the wound dressd. and litters made to carry
          them in</action>, <action actCat="movement" who="US Army">the Army then movd. forwarward within sight of the
          British Garison where the Army incampd on a high Bank in a thick 
          Brush.</action> <description desCat="commentary">the Action was General and conducted with propriety and
          honour to the American Arms and <person pID="01">Their Officer</person></description> <description desCat="landscape">in sight of the
          army was the River divided by a large Island well Cultivated with
          Corn &amp; beans and a number of Stacks of Hay which was a pleaseing
          sight to the Army but more particularly to the Volunteers that was
          across the River and bringing loads of Corn and Hay in one hour
          after the army got to the ground</description> under the Guns of the British
          Garison <description desCat="weather">a <weather>smart Shower of Rain</weather> after the action</description>.
				</para>
			</account>
  </ftAccount>
</ftAccounts>

=== ryales/fallen_timbers/xml/02.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ftaccounts.xsl"?>

<ftAccounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ftAccounts.xsd">
  <ftAccount id="02">
    <bibInfo medium="journal" distance="primary" format="book" text="edited_reprint">
      <pubTitle>A Precise Journal of General Wayne's Last Campaign in the year 1794, against the western Indians, taken down in the course of the campaign: With an account of an attack made of an attack made on Fort Recovery, by the Indians, on the 30th June preceding</pubTitle>
      <pubAuthor>
        <person pID="49">
          <pSurname>Randolph</pSurname>
        </person>
      </pubAuthor>
      <pubEditor>
        <person pID="50">
          <pGiven>Richard C.</pGiven>
          <pSurname>Knopf</pSurname>
        </person>
      </pubEditor>
      <pubName>American Antiquarian Society</pubName>
      <pubDate date="1954">1954</pubDate>
      <pubPage>290-291</pubPage>
    </bibInfo>
    <account>
      <header>
        <date when="1794-08-20">AUGUST 20th.</date>
      </header>
      <para>
        <description desCat="weather">Prevented from marching this Morning at the appointed Hour
        by <weather>Rain</weather></description>; but <action actCat="movement" who="US Army">at 7 o'Clock the Line of March is taken up and continued
        in the most perfect Order for four Miles</action>, when <action actCat="battle" who="Front Guard">a Firing
        commenced in <unit name="Front Guard">Front</unit></action>; in a few Moments <action actCat="movement" who="Front Guard">our <unit name="Front Guard">advanced Parties</unit>
        were compelled to retire by a superior Number</action>. In the Interim
        <action actCat="mobilization" who="US Legion">the <unit name="US Legion">Legion</unit> was formed in two Lines</action>, but <action actCat="battle" who="US Army">the <person pID="01"><pTitle>Commander in Chief</pTitle></person>
        finding the Enemy were gaining our left Flank, ordered the <unit name="Rear Guard">Rear
        Line</unit> to advance to support the <unit name="Front Guard">Front</unit></action>&#8212;This done, and <action actCat="battle" who="US Army">the Whole
        formed now in one sustaining front Line, a Charge was ordered,
        in which the Enemy were routed and compelled to retire one Mile
        in one Hour</action>. When the Pursuit was left, <action actCat="rest" who="US Legion">the Legion halted and
        refreshed with an Issue of some Spirits</action>&#8212;<action actCat="burial" who="US Army">our Killed and Wounded
        collected, the former enterred, the latter dressed and sent to Camp
        Deposit</action>. <action actCat="casualty" who="US Officers">Among the Killed was that good, brave, gallant and
        intrepid <person pID="05"><pRank>Captain</pRank> <pGiven>Robert</pGiven> <pSurname>Mis Campbell</pSurname></person>, of the <unit name="Right Dragoons">second Troop
        Light Dragoons</unit>, and then commanding Officer of the Cavalry,
        who fell in a Charge on the Enemy in an early Part of the Action</action>;
        by which <description desCat="obituary">the Legion was deprived of one of its bravest Officers,
        before he had an Opportunity of rendering his Country those
        Services which were to be expected from his Bravery. It would
        be vain for Abilities like mine to attempt to describe the deceased
        <person pID="05"><pRank>Captain</pRank> <pSurname stSurname="Mis Campbell">Campbell</pSurname></person>'s Virtues; but to do Justice to his Memory <person pID="49">I</person>
        cannot avoid observing, he was possessed of every Qualification
        which constitutes the Gentleman, the Officer and a good Man:
        and as he was when living generally loved, now that he is dead
        description believe he is as generally lamented.</description>
      </para>
      <para>
        <action actCat="casualty" who="US Officers"><person pID="04"><pRank>Lieutenant</pRank> <pGiven stGiven="Henry Beverly">Henry B.</pGiven> <pSurname>Towles</pSurname></person>, a brave and gallant Officer of the
        4th Sub-Legion Light-Infantry, was also killed in the Course of
        this Action</action>, and <action actCat="casualty" who="US Officers">several other intrepid Officers wounded</action>.
      </para>
      <para>
        During the <action actCat="movement" who="US Legion">Halt of the Legion at this Place</action>, and while <description desCat="position">the right
        Flankers were in Advance of the Army half a Mile</description>, <action actCat="prisoner" who="US Army">a Canadian was
        taken, who was painted and dressed like an Indian Warrior</action>. <action actCat="movement" who="US Army">In
        one half Hour the Whole moved some Distance father down the
        River and within half a Mile of the Fort, where we were halted
        and encamped under the Guns of said Garrison</action>, from which <action actCat="diplomacy">a
        Flag was this Afternoon received&#8212;its Purport unknown</action>.
      </para>
      <para>
        <action actCat="movement" who="US Army">Advanced six Miles this Day</action>.
      </para>
    </account>
  </ftAccount>
</ftAccounts>
