=== ryales/fallen_timbers/ftAccounts.xsd
<?xml version="1.0"?>

<!-- RACHEL YALES                              -->
<!-- INSTG037 XML FINAL PROJECT                -->
<!-- INSTRUCTOR: SIMON MAHONY                  -->
<!-- SCHEMA FOR FALLEN TIMBERS BATTLE ACCOUNTS -->

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  	<!-- ROOT ELEMENT -->
  	<xs:element name="ftAccounts">
      <xs:complexType>
        <xs:sequence>
          <!-- ELEMENT FOR EACH INDIVIDUAL ACCOUNT: NO UPPER LIMIT ON NUMBER OF DOCUMENTS -->
          <xs:element name="ftAccount" maxOccurs="unbounded">
            <xs:complexType mixed="true">
              <xs:sequence>
                <!-- BIBLIOGRAPHIC INFO ABOUT THE DOCUMENT SOURCE -->
                <xs:element name="bibInfo">
                  <xs:complexType>
                    <!-- ONLY 0 OR 1 OF EACH ELEMENT: ORDER DOES NOT MATTER -->
                    <xs:all>
                      <xs:element name="pubArticle" type="xs:string" minOccurs="0"/>
                      <xs:element name="pubTitle" type="xs:string"/>
                      <!-- PUBAUTHOR CALLS TO GLOBAL PERSON ELEMENT -->
                      <xs:element name="pubAuthor">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element ref="person"/>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <!-- PUBEDITOR CALLS TO GLOBAL PERSON ELEMENT -->
                      <xs:element name="pubEditor" minOccurs="0">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element ref="person"/>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="pubName" type="xs:string"/>
                      <xs:element name="pubVol" type="xs:integer" minOccurs="0"/>
                      <xs:element name="pubIss" type="xs:integer" minOccurs="0"/>
                      <xs:element name="pubColl" type="xs:string" minOccurs="0"/>
                      <!-- PUBPLACE IS AN EMPTY ELEMENT WITH ATTRIBUTES -->
                      <xs:element name="pubPlace" minOccurs="0">
                        <xs:complexType>
                          <xs:attribute name="city" type="xs:string"/>
                          <xs:attribute name="state" type="xs:string"/>
                          <xs:attribute name="country" type="xs:string"/>
                        </xs:complexType>
                      </xs:element>
                      <!-- PUBDATE HAS DATATYPE GYEAR BECAUSE NO NEED FOR SPECIFIC DATE -->
                      <xs:element name="pubDate" minOccurs="0">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="date" type="xs:gYear"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="pubPage" type="xs:string" minOccurs="0"/>
                    </xs:all>
                    <!-- BIBINFO ATTRIBUTES CLASSIFY DOCUMENT SOURCE -->
                    <xs:attribute name="medium" type="xs:string" use="required"/>
                    <xs:attribute name="distance" type="xs:string" use="required"/>
                    <xs:attribute name="format" type="xs:string" use="required"/>
                    <xs:attribute name="text" type="xs:string" use="required"/>
                  </xs:complexType>
                </xs:element>
                <!-- DOCUMENT TEXT -->
                <xs:element name="account">
                  <xs:complexType>
                    <xs:sequence>
                      <!-- NOT EVERY DOCUMENT HAS HEADER -->
                      <!-- CALLS TO GLOBAL ELEMENTS -->
                      <xs:element name="header" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:element ref="place"/>
                            <xs:element ref="date"/>
                          </xs:choice>
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE OPENINGS -->
                      <xs:element name="opening" minOccurs="0">
                        <xs:complexType mixed="true">
                        </xs:complexType>
                      </xs:element>
                      <!-- UNLIMITED NUMBER OF PARAGRAPHS ALLOWED -->
                      <!-- CALLS TO GLOBAL ELEMENTS -->
                      <xs:element name="para" maxOccurs="unbounded">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                              <xs:element ref="action"/>
                              <xs:element ref="description"/>
                            </xs:choice>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE CLOSINGS -->
                      <xs:element name="closing" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                              <xs:element ref="person"/>
                            </xs:choice>
                          </xs:sequence> 
                        </xs:complexType>
                      </xs:element>
                      <!-- LETTER DOCUMENTS HAVE ADDRESSEE SECTION -->
                      <xs:element name="addressee" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                              <xs:element ref="person"/>
                            </xs:choice>
                          </xs:sequence>    
                        </xs:complexType>
                      </xs:element>
                      <!-- SOME LETTER DOCUMENTS HAVE POSTSCRIPTS -->
                      <xs:element name="postscript" minOccurs="0">
                        <xs:complexType mixed="true">
                          <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                              <xs:element ref="action"/>
                              <xs:element ref="description"/>
                            </xs:choice>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <!-- EACH FTACCOUNT HAS UNIQUE ID -->
              <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:complexType> 
          </xs:element>
        </xs:sequence>
      </xs:complexType>
  	</xs:element>
    
    <!-- GLOBAL ELEMENTS CONTAINED BELOW -->
    <!-- CAN BE USED IN MULTIPLE CONTEXTS -->
    <xs:element name="person">  
      <xs:complexType mixed="true">
        <xs:all>
          <xs:element name="pRank" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stRank" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>
          <xs:element name="pGiven" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stGiven" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
          <xs:element name="pSurname" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stSurname" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
          <xs:element name="pTitle" minOccurs="0">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="stTitle" type="xs:string"/>
                </xs:extension>
              </xs:simpleContent>
             </xs:complexType>
          </xs:element>
        </xs:all>
        <!-- Each unique person required to have an ID -->
        <xs:attribute name="pID" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="place">  
      <xs:complexType  mixed="true">
        <xs:attribute name="lat" type="xs:float"/>
        <xs:attribute name="long" type="xs:float"/>
        <!-- Each unique place required to have an ID -->
        <xs:attribute name="placeID" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="date">  
      <xs:complexType  mixed="true">
        <xs:attribute name="when" type="xs:date"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="unit">  
      <xs:complexType  mixed="true">
        <xs:attribute name="name" type="xs:string"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="action">  
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="person"/>
            <xs:element ref="unit"/>
            <xs:element ref="place"/>
            <xs:element ref="date"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="actCat" type="xs:string" use="required"/>
        <xs:attribute name="who" type="xs:string"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="description">  
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="person"/>
            <xs:element ref="unit"/>
            <xs:element ref="place"/>
            <xs:element ref="date"/>
            <xs:element name="weather">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="weatherID" type="xs:string"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="desCat" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:element>
  </xs:schema>

=== ryales/fallen_timbers/xml/01.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ftaccounts.xsl"?>

<ftAccounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ftAccounts.xsd">
  <ftAccount id="01">
    <bibInfo medium="journal" distance="primary" format="book" text="edited_reprint">
      <pubTitle>Journal, Thomas Taylor Underwood, March 26, 1792 to March 18, 1800: An Old Soldier in Wayne's Army</pubTitle>
      <pubAuthor>
        <person pID="21">
          <pGiven>Thomas Taylor</pGiven>
          <pSurname>Underwood</pSurname>
        </person>
      </pubAuthor>
      <pubName>The Society of Colonial Wars in the State of Ohio</pubName>
      <pubPlace city="Cincinnati" state="Ohio"/>
      <pubDate date="1945">1945</pubDate>
      <pubPage>17-18</pubPage>
    </bibInfo>
    <account>
      <header>
        <place placeID="01" lat="41.487992" long="-83.729863">Camp Deposite</place>, the <date
          when="1794-08-20">20th August 1794</date>&#8212;
      </header>
      <para>
        <action actCat="mobilization" who="US Army">This morning the army was under arms, at day light and our line of march arranged. </action>
        <description desCat="position"><person pID="04"><pRank stRank="Lieutenant">Lietenant</pRank> <pGiven stGiven="Henry Beverly">Hary Beverly</pGiven> <pSurname>Towles</pSurname></person> was detailed to take command of <unit name="Front Guard">the front guard</unit>, he was ordered to march on in front,</description>
        <action actCat="movement" who="US Army">the main army commenced there march</action>, <description desCat="position"><person pID="06"><pRank>General</pRank> <pGiven>Charles</pGiven> <pSurname>Scott</pSurname></person> with his mounted Volunteers were placed in <unit name="Rear Guard">the rear</unit>
        </description>. After <action actCat="movement" who="US Army">marching 3 or 4 miles </action><action actCat="battle" who="Front Guard">the front guard was fired on</action>, &amp; the <action actCat="casualty" who="Front Guard"> most of them either killed or wounded</action>.
        <action actCat="casualty" who="Front Guard"><person pID="04"><pRank stRank="Lieutenant">Lieut.</pRank> <pGiven stGiven="Harry Beverly">H. B.</pGiven> <pSurname>Towles</pSurname></person> was killed</action>, <action actCat="casualty" who="Front Guard">also
        his sergeant, By the name of <person pID="07"><pGiven>Eli</pGiven> <pSurname>Edmondson</pSurname></person></action>.
        <action actCat="mobilization" who="Legion"> The army was immediately formed for Action</action>, which very soon
        began, <action actCat="battle"> it commenced on the right of the army, &amp; on the margin of the River</action>,
        <description desCat="position"><person pID="08"><pRank>Lieutenant</pRank> <pGiven>Percy</pGiven> <pSurname>Pope</pSurname> </person> commanded <person pID="09"> <pRank>Capt.</pRank> <pGiven>John</pGiven> <pSurname>Price</pSurname> </person>s
        <unit>company of artillery</unit> and he was the first officer that fired a shot from our
        howitzers</description>. Several of the first shots was with shell then he commenced with grape
        &amp; cannister shot. <description desCat="landscape">On front &amp; between the indians was a large quantity of
        falling down Timber, which was a shelter for the indians, where they remained some
        time</description>, <action actCat="battle" who="Native Confederacy">they would load &amp; fire then fall down &amp; load, then rise
        and fire again</action>. <action actCat="battle" who="US Legion">A Charge was very soon ordered by the <person pID="01"><pTitle>Commander in
        chief</pTitle></person></action>, <action actCat="movement" who="Native Confederacy">the indians soon retreated</action>
        <action actCat="Casualty" who="Native Confederacy">they had a great many killed</action>, <action actCat="burial" who="Native Confederacy">they threw a number of there dead in
        the River</action>. <action actCat="movement" who="Rear Guard"><person pID="06"><pRank>General</pRank> <pSurname>Scott</pSurname></person> was ordered to try and seround
        the indians</action>, but <action actCat="movement" who="Native Confederacy">they got aprized of it &amp; retreated as fast as
        possible</action>&#8212;
      </para>
      <para>
          <action actCat="casualty" who="US Officers"><person pID="05"><pRank stRank="Captain">Capt.</pRank> <pGiven>Robert</pGiven> <pSurname>Mis Campbell</pSurname></person> &amp; <person pID="04"><pRank>Lieutenant</pRank> <pGiven stGiven="Harry Beverly">Harry B.</pGiven>
          <pSurname>Towles</pSurname></person> were killed and several officers badly wounded.
          <person pID="10"><pRank>Lieutenant</pRank> <pGiven>Solomon</pGiven> <pSurname stSurname="Van Rensselaer">Vanranceller</pSurname></person> was shot in the right breast and
          taken to the Generals Quarters</action>, <action actCat="casualty" who="Front Guard"><person pID="11"><pGiven>John</pGiven> <pSurname stSurname="O'Brion">OBrion</pSurname></person> was with the
          front guard this morning, &amp; on the retreat he was shot in the low part of his back, the
          ball passed through the bottom of his Belly &amp; lodged in a certain part in front, in his
          P&#8212;&#8212;</action> After <action actCat="burial" who="US Army">entured the dead with the Honors of War</action>
          <action actCat="movement" who="US Army">the army marched back to Camp deposite</action>, we have <action actCat="prisoner" who="Native Confederacy">heard that the
          indians Burnt poor <person pID="12"><pGiven>George</pGiven> <pSurname>May</pSurname></person> who they took prisoner 19th inst.</action>
      </para>
    </account>
  </ftAccount>
</ftAccounts>

=== ryales/fallen_timbers/xml/09.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ftaccounts.xsl"?>

<ftAccounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ftAccounts.xsd">
  <ftAccount id="09">
    <bibInfo medium="letter" distance="primary" format="letter" text="edited_reprint">
      <pubArticle>
        From William Campbell to R.G. England
      </pubArticle>
      <pubAuthor>
        <person pID="03">
          <pRank>Major</pRank>
          <pGiven>William</pGiven>
          <pSurname>Campbell</pSurname>
        </person>
      </pubAuthor>
      <pubEditor>
        <person pID="48">
          <pRank>Brigadier General</pRank>
          <pGiven>E. A.</pGiven>
          <pSurname>Cruikshank</pSurname>
        </person>
      </pubEditor>
      <pubTitle>
        The Correspondence of Lieut. Governor John Graves Simcoe, with Allied Documents relating to his Administration of the Government of Upper Canada
      </pubTitle>
      <pubVol>
        2
      </pubVol>
      <pubName>
        Ontario Historical Society
      </pubName>
      <pubDate date="1924"></pubDate>
      <pubPlace city="Toronto" state="Ontario" country="Canada"></pubPlace>
      <pubPage>
        395-396
      </pubPage>
    </bibInfo>
    <account>
      <header>
        <place placeID="04">Fort Miamis</place>, <date when="1794-08-20">August 20th, 1794</date>.
      </header>

      <opening>
        My Dear Colonel,
      </opening>

      <para>
        <person>I</person> did myself the pleasure to write to you this morning about seven o'clock by
        <person>Mr. Montigny</person>. Since when we have passed a very odd kind of day. Within
        less than an hour after he set off <action actCat="battle">a very brisk fire commenced a little higher up than
        opposite to <person>Colonel McKee</person>'s, and increased until near 11 o'clock</action>, when <action actCat="movement" who="Native Confederacy">we found
        a number of Indians coming down upon us in the open, but by far the greatest
        number of them had been noticed under cover of the wood at some distance in our
        Front</action>. <action>This fire had for some time no other effect upon our working parties than
        to frighten our Canadians and it was with a good deal of difficulty we could prevail
        on them not to run away</action>, but as they said to take to their Arms. However, at
        last it became so serious that <person>I</person> thought it high time to stand to our Arms, fill up
        all gaps in our Abatis and shut out all communications from the Fort, by fixing our
        Chevaux de Frise, &amp;c., &amp;c., not knowing at what moment we might be attacked.
        The fact was&#8212;the Americans and Indians had come to action and the latter were
        defeated. Some of the Nations fought well but were outgeneralled. The Wyandots,
        they say, have lost the most, but the loss of men altogether is not great on
        the part of the Indians. <action actCat="casualty" who="Native Confederacy">Poor <person>Agushway</person> is shot through the head but not killed.</action>
        <action actCat="casualty" who="Native Confederacy">The <person>Little Otter</person> was killed and several other Chiefs.</action> The Americans, they say,
        have lost a number. Accounts, you may believe, vary. Some make it out as
        high as 400 but this <person>I</person> do not credit&#8212;be that as it may, they seem to have completely
        gained their point. <action>We see them now feeding their horses upon <person>Colonel McKee</person>'s
        Island, and on this side showing themselves in small bodies very near to us, beating
        their drums and sounding their horns.</action> <action><person>Colonel McKee</person>, who has been constantly
        with the Indians for several days past, called on <person>me</person> as <person>he</person> passed down, and acknowledged
        they were outgeneraled.</action> <action>The Indians are now totally gone away and
        <person>I</person> believe towards the Mouth of the River</action>, though <person>he</person> said they were still in spirits
        and determined to give them another brush. <description>It has been a great relief to my mind
                that the Battle did not happen so near to this Fort, so as to commit <person>me</person>.</description> You
        will perceive by this that <description><person>I</person> still do not expect him to storm our Works. At the same time <person>I</person>
                shall act in every respect in the safety of the Post as if <person>I</person> did.</description> <action>The only
        thing <person>I</person> am in difficulty about is to say how far safe it would be for you to send us
        a reinforcement. If <person>I</person> was to hazard an opinion, <person>I</person> would think it safe and it will
        give all here great pleasure to see them.</action> <action>As <person>I</person> send this to <person>Colonel McKee</person> to be
        forwarded to you</action> <person>I</person> hope he may be better able to give you information on this
        head. In case of any alteration of circumstances, <person>I</person> shall never lose sight of it.
      </para>

      <para>
        <action><person>I</person> expect this will find <person>Colonel McKee</person> near <place placeID="05">Point Au Chen</place>e</action>&#8212;<description>Would to God
        <person>the Governor</person> himself were here. Whatever happens <person>I</person> shall do for the best. No
        one can do more.</description> <person>You</person> shall soon hear from me again. Meantime allow me to
        subscribe myself.
      </para>

      <closing>
        Ever most faithfully and truly,
        <person>Wm. Campbell</person>.
      </closing>

      <postscript>
        P.S.&#8212;<action><person>Lt. Selbie</person> arrived about three o'clock with your dispatch of the 18th
        by which I was extremely happy to find all well at Detroit.</action> <action><person>Captain Harrow</person>
        and his six sailors are still here.</action> To-morrow morning will probably decide me
        whether to keep him or not. When we manned our work this morning at Reveille
        beating, <description>we mustered 160 Rank and File of the 24th, Queen's Rangers, and Artillery,
        (<person>I</person> beg the Artillery's pardon), exclusive of Canadians and artificers. We have
        <person>Captain</person> and about 24 Canadians.</description>
      </postscript>
    </account>
  </ftAccount>
</ftAccounts>
